export type CategoryId =
  | "everyday-life"
  | "food-culture"
  | "science-nature"
  | "places-geography"
  | "history"
  | "games-tech"
  | "fiction-entertainment"
  | "abstract-concepts";

export type DifficultyId = "normal" | "hard" | "extreme";

export type GeneratedCard = {
  id: string;
  text: string;
  categoryId: CategoryId;
  categoryName: string;
  difficulty: DifficultyId;
};

export const CARDS_PER_PACK = 2000;

export const CATEGORY_PACKS: Array<{
  id: CategoryId;
  name: string;
  description: string;
}> = [
  {
    id: "everyday-life",
    name: "Everyday Life",
    description: "Household moments, jobs, transport, errands, tools, and daily routines.",
  },
  {
    id: "food-culture",
    name: "Food & Culture",
    description: "Dishes, drinks, rituals, festivals, manners, and shared traditions.",
  },
  {
    id: "science-nature",
    name: "Science & Nature",
    description: "Animals, weather, planets, biology, physics, and natural processes.",
  },
  {
    id: "places-geography",
    name: "Places & Geography",
    description: "Countries, cities, landmarks, landscapes, maps, and journeys.",
  },
  {
    id: "history",
    name: "History",
    description: "Events, inventions, eras, leaders, discoveries, and old-world drama.",
  },
  {
    id: "games-tech",
    name: "Games & Tech",
    description: "Video games, gadgets, software, inventions, robots, and digital life.",
  },
  {
    id: "fiction-entertainment",
    name: "Fiction & Entertainment",
    description: "Movies, books, shows, stage moments, characters, music, and fame.",
  },
  {
    id: "abstract-concepts",
    name: "Abstract Concepts",
    description: "Ideas, feelings, systems, invisible forces, and big human questions.",
  },
];

export const DIFFICULTIES: Array<{
  id: DifficultyId;
  name: string;
  description: string;
}> = [
  {
    id: "normal",
    name: "Normal",
    description: "Recognizable prompts most groups can act out quickly.",
  },
  {
    id: "hard",
    name: "Hard",
    description: "More specific prompts that need clever structure and signals.",
  },
  {
    id: "extreme",
    name: "Extreme",
    description: "Obscure, abstract, or layered prompts for chaos-loving teams.",
  },
];

const frameTemplates: Record<DifficultyId, string[]> = {
  normal: [
    "{subject}",
    "using {subject}",
    "looking for {subject}",
    "finding {subject}",
    "carrying {subject}",
    "cleaning {subject}",
    "fixing {subject}",
    "sharing {subject}",
    "dropping {subject}",
    "hiding {subject}",
    "waiting for {subject}",
    "running away from {subject}",
    "teaching someone about {subject}",
    "drawing {subject} in the air",
    "packing {subject}",
    "choosing {subject}",
    "forgetting {subject}",
    "celebrating {subject}",
    "being surprised by {subject}",
    "pretending to be {subject}",
    "explaining {subject}",
    "protecting {subject}",
    "trading {subject}",
    "pointing at {subject}",
    "discovering {subject}",
  ],
  hard: [
    "misunderstanding {subject}",
    "trying to explain {subject}",
    "building a model of {subject}",
    "solving a problem with {subject}",
    "arguing about {subject}",
    "escaping because of {subject}",
    "repairing {subject} under pressure",
    "recognizing {subject} too late",
    "training someone to use {subject}",
    "making a silent warning about {subject}",
    "turning {subject} into a plan",
    "losing control of {subject}",
    "searching for proof of {subject}",
    "acting suspicious around {subject}",
    "getting blamed for {subject}",
    "inventing a shortcut for {subject}",
    "using {subject} as a clue",
    "accidentally revealing {subject}",
    "being trapped by {subject}",
    "organizing a rescue involving {subject}",
    "secretly studying {subject}",
    "testing {subject} without instructions",
    "defending {subject} from critics",
    "making a bad deal over {subject}",
    "pretending not to know {subject}",
  ],
  extreme: [
    "the hidden logic of {subject}",
    "a conspiracy built around {subject}",
    "explaining {subject} to aliens",
    "surviving a disaster caused by {subject}",
    "a courtroom debate about {subject}",
    "a silent documentary about {subject}",
    "the final warning before {subject}",
    "a ritual dedicated to {subject}",
    "a world where {subject} is illegal",
    "an impossible machine powered by {subject}",
    "a prophecy misunderstood as {subject}",
    "a detective solving {subject}",
    "a villain obsessed with {subject}",
    "the emotional damage of {subject}",
    "a museum exhibit about {subject}",
    "a fake expert explaining {subject}",
    "a secret society protecting {subject}",
    "a last-minute escape from {subject}",
    "a dream sequence about {subject}",
    "a public scandal involving {subject}",
    "a survival guide for {subject}",
    "a magic spell that creates {subject}",
    "a time traveler preventing {subject}",
    "a haunted version of {subject}",
    "a negotiation ruined by {subject}",
  ],
};

const contextTemplates: Record<CategoryId, Record<DifficultyId, string[]>> = {
  "everyday-life": {
    normal: ["at home", "before work", "in a busy shop", "during a weekend"],
    hard: ["during a power cut", "while already late", "in a shared apartment", "with no instructions"],
    extreme: ["during a neighborhood emergency", "inside a tiny elevator", "while everyone is watching", "after the warranty expired"],
  },
  "food-culture": {
    normal: ["at dinner", "at a street market", "during a family visit", "at a picnic"],
    hard: ["during a cooking contest", "at a formal ceremony", "with a secret recipe", "while serving guests"],
    extreme: ["at a royal banquet", "during a cultural misunderstanding", "inside a fusion restaurant", "at a festival gone wrong"],
  },
  "science-nature": {
    normal: ["outside", "in a classroom", "during a storm", "at the zoo"],
    hard: ["inside a laboratory", "during a field study", "under a microscope", "on a research trip"],
    extreme: ["at the edge of space", "inside a collapsing ecosystem", "during an impossible experiment", "in front of a skeptical professor"],
  },
  "places-geography": {
    normal: ["on holiday", "with a map", "at the airport", "during a road trip"],
    hard: ["while crossing a border", "during a lost expedition", "with broken GPS", "on a confusing tour"],
    extreme: ["during a geopolitical crisis", "in a disputed territory", "on an ancient trade route", "while redrawing the map"],
  },
  history: {
    normal: ["in an old classroom", "at a museum", "during a parade", "in a costume"],
    hard: ["during a revolution", "while reading an old letter", "inside an archive", "before a famous speech"],
    extreme: ["while rewriting the timeline", "during a secret treaty", "at a trial centuries later", "after the empire falls"],
  },
  "games-tech": {
    normal: ["on the couch", "with a controller", "at a desk", "during a video call"],
    hard: ["during a tournament", "while debugging", "after the battery dies", "inside a crowded server room"],
    extreme: ["inside a simulated reality", "during a system takeover", "while the network collapses", "against an impossible final boss"],
  },
  "fiction-entertainment": {
    normal: ["on stage", "at the cinema", "during karaoke", "in a bookshop"],
    hard: ["during an audition", "at a fan convention", "while filming one take", "during a plot twist"],
    extreme: ["inside a crossover universe", "during a cursed performance", "after the fourth wall breaks", "at the villain's press conference"],
  },
  "abstract-concepts": {
    normal: ["with body language only", "between two friends", "during an argument", "in a quiet room"],
    hard: ["inside a moral dilemma", "during a public debate", "while making a promise", "under social pressure"],
    extreme: ["as a physical object", "during a philosophical crisis", "inside a dream court", "after reality changes the rules"],
  },
};

const subjects: Record<CategoryId, Record<DifficultyId, string[]>> = {
  "everyday-life": {
    normal: [
      "a toothbrush",
      "a washing machine",
      "a grocery cart",
      "a bus stop",
      "a lost key",
      "a lunchbox",
      "a vacuum cleaner",
      "a leaking tap",
      "a phone charger",
      "a mailbox",
      "a bicycle helmet",
      "a shopping list",
      "a coffee mug",
      "a doorbell",
      "a backpack",
      "a pair of shoes",
      "a remote control",
      "a calendar",
      "a taxi ride",
      "a trash bag",
    ],
    hard: [
      "a tripped circuit breaker",
      "flat-pack furniture",
      "a smoke detector battery",
      "a jammed printer",
      "a tax receipt",
      "a parking meter",
      "a clogged drain",
      "a house inspection",
      "a missed delivery slip",
      "a rental agreement",
      "a broken zipper",
      "a group chat misunderstanding",
      "a baby monitor",
      "a car service warning",
      "a lost luggage tag",
      "a public transport transfer",
      "a home security alarm",
      "a password reset",
      "a building intercom",
      "a water bill",
    ],
    extreme: [
      "a notarized document",
      "a disputed utility deposit",
      "a warranty loophole",
      "a homeowners association rule",
      "an expired safety certificate",
      "a broken boiler pressure valve",
      "a mystery subscription charge",
      "an insurance claim form",
      "a faulty smart thermostat",
      "a mislabeled storage unit",
      "a neighborhood noise complaint",
      "a power-of-attorney letter",
      "an emergency evacuation drill",
      "a recalled appliance",
      "a landlord inventory checklist",
      "a jury duty summons",
      "a confusing medicine label",
      "a shared custody schedule",
      "a workplace fire marshal",
      "a biometric door lock",
    ],
  },
  "food-culture": {
    normal: [
      "pizza",
      "sushi",
      "birthday cake",
      "hot chocolate",
      "tacos",
      "ice cream",
      "barbecue",
      "pancakes",
      "popcorn",
      "a sandwich",
      "noodles",
      "a food truck",
      "a tea ceremony",
      "a picnic basket",
      "a cooking pot",
      "a wedding toast",
      "chopsticks",
      "a buffet",
      "a farmers market",
      "a recipe book",
    ],
    hard: [
      "sourdough starter",
      "kimchi",
      "tiramisu",
      "ramen broth",
      "paella",
      "falafel",
      "fermented tea",
      "a spice grinder",
      "a tasting menu",
      "a dumpling fold",
      "a street festival",
      "a harvest ritual",
      "a ceremonial drum",
      "a family recipe dispute",
      "a food allergy warning",
      "a Michelin inspector",
      "a market haggle",
      "a tea leaf reading",
      "a midnight feast",
      "a shared bread basket",
    ],
    extreme: [
      "molecular gastronomy",
      "a saffron harvest",
      "a truffle auction",
      "a ceremonial fast",
      "a diaspora recipe",
      "an edible gold dessert",
      "a forbidden banquet",
      "a culinary taboo",
      "a lost fermentation jar",
      "an ancient grain revival",
      "a sacred offering plate",
      "a spice route rivalry",
      "a royal food taster",
      "a mythical feast",
      "a misread etiquette rule",
      "a ghost kitchen empire",
      "a counterfeit wine label",
      "a ritual tea whisk",
      "a ceremonial mask dance",
      "a secret noodle technique",
    ],
  },
  "science-nature": {
    normal: [
      "a thunderstorm",
      "a butterfly",
      "a volcano",
      "the Moon",
      "a rainbow",
      "a dolphin",
      "a cactus",
      "a magnet",
      "a telescope",
      "a microscope",
      "a honeybee",
      "a waterfall",
      "a dinosaur",
      "a snowflake",
      "a spider web",
      "a planet",
      "a fossil",
      "gravity",
      "a seed",
      "a wave",
    ],
    hard: [
      "photosynthesis",
      "evaporation",
      "a black hole",
      "plate tectonics",
      "a coral reef",
      "a solar eclipse",
      "migration",
      "an electric circuit",
      "a food chain",
      "a lunar eclipse",
      "a pressure system",
      "camouflage",
      "hibernation",
      "a chemical reaction",
      "a DNA strand",
      "a meteor shower",
      "a sound wave",
      "a glacier",
      "a parasite",
      "an earthquake fault",
    ],
    extreme: [
      "quantum entanglement",
      "dark matter",
      "continental drift",
      "symbiotic fungi",
      "neural plasticity",
      "genetic drift",
      "redshift",
      "superconductivity",
      "a tardigrade",
      "ocean acidification",
      "a double-slit experiment",
      "epigenetics",
      "a neutrino detector",
      "recursive evolution",
      "a rogue planet",
      "antimatter",
      "mycelium networks",
      "entropy",
      "a gravitational wave",
      "a mass extinction",
    ],
  },
  "places-geography": {
    normal: [
      "the Eiffel Tower",
      "a beach",
      "New York City",
      "a desert",
      "Mount Everest",
      "a castle",
      "a train station",
      "a rainforest",
      "a village",
      "a bridge",
      "a lighthouse",
      "a farm",
      "a city bus",
      "a map",
      "a passport",
      "a hotel lobby",
      "a mountain",
      "an island",
      "a river",
      "an airport",
    ],
    hard: [
      "the Panama Canal",
      "a fjord",
      "the Sahara Desert",
      "the Great Barrier Reef",
      "a border crossing",
      "an archipelago",
      "a time zone",
      "a mountain pass",
      "a subway map",
      "a ferry terminal",
      "a pilgrimage route",
      "a national park ranger",
      "a customs officer",
      "a volcanic island",
      "a river delta",
      "a monsoon season",
      "a remote research station",
      "a hidden valley",
      "a canal lock",
      "a trade route",
    ],
    extreme: [
      "an exclave",
      "a disputed border",
      "a cartographer's error",
      "the International Date Line",
      "a microstate",
      "a former colony",
      "a ghost town",
      "an ancient migration path",
      "a maritime boundary",
      "a landlocked navy",
      "a tectonic boundary",
      "a desertification front",
      "a sacred mountain pass",
      "a lost city",
      "a polar research treaty",
      "a geopolitical buffer zone",
      "a cultural crossroads",
      "a vanishing island",
      "a linguistic border",
      "a map projection",
    ],
  },
  history: {
    normal: [
      "a knight",
      "a pirate ship",
      "a crown",
      "a steam train",
      "an ancient pyramid",
      "a castle siege",
      "a gold rush",
      "a museum guide",
      "a typewriter",
      "a horse carriage",
      "a space landing",
      "a peace sign",
      "a royal wedding",
      "a scroll",
      "a famous speech",
      "an old map",
      "a candlelit room",
      "a printing press",
      "a battlefield flag",
      "a treasure chest",
    ],
    hard: [
      "the Renaissance",
      "the Industrial Revolution",
      "a coded telegram",
      "the Silk Road",
      "a medieval guild",
      "a Roman senate",
      "a Viking raid",
      "a suffrage march",
      "a Cold War bunker",
      "a moon mission control room",
      "a treaty signing",
      "a prohibition speakeasy",
      "an archaeological dig",
      "a plague doctor",
      "a merchant caravan",
      "a naval blockade",
      "a propaganda poster",
      "a royal succession crisis",
      "a scientific discovery",
      "a civil rights sit-in",
    ],
    extreme: [
      "the fall of Constantinople",
      "a forgotten dynasty",
      "a diplomatic backchannel",
      "the Treaty of Westphalia",
      "a palace coup",
      "a disputed succession",
      "a deciphered manuscript",
      "a failed expedition",
      "a colonial border line",
      "a revolutionary pamphlet",
      "a medieval heresy trial",
      "a secret armistice",
      "a vanished library",
      "a forged royal decree",
      "an ancient irrigation system",
      "a war of succession",
      "a lost explorer's journal",
      "an imperial census",
      "a resistance network",
      "a historical revision",
    ],
  },
  "games-tech": {
    normal: [
      "a video game controller",
      "a smartphone",
      "a laptop",
      "a robot",
      "a password",
      "a selfie",
      "a drone",
      "a racing game",
      "a joystick",
      "a charging cable",
      "a smartwatch",
      "a headset",
      "a keyboard",
      "a mouse",
      "a game console",
      "a text message",
      "a printer",
      "a camera",
      "a tablet",
      "a video call",
    ],
    hard: [
      "a firewall",
      "a speedrun",
      "virtual reality",
      "a software update",
      "a broken server",
      "a captcha",
      "a boss battle",
      "a loot box",
      "a search algorithm",
      "a 3D printer",
      "a motion sensor",
      "a cloud backup",
      "a corrupted save file",
      "a phishing email",
      "a smart home routine",
      "a patch note",
      "a lag spike",
      "a debugging session",
      "a multiplayer lobby",
      "an encrypted message",
    ],
    extreme: [
      "machine learning bias",
      "a zero-day exploit",
      "quantum computing",
      "a blockchain fork",
      "a neural interface",
      "a dead pixel conspiracy",
      "a rogue AI assistant",
      "a distributed denial attack",
      "a procedural universe",
      "a corrupted simulation",
      "a reverse-engineered console",
      "a forgotten root password",
      "a sandbox escape",
      "a sentient chatbot",
      "an algorithmic recommendation spiral",
      "a speedrunner's frame trick",
      "a server migration disaster",
      "a biometric spoof",
      "a virtual economy crash",
      "a robot ethics hearing",
    ],
  },
  "fiction-entertainment": {
    normal: [
      "a movie star",
      "a superhero",
      "a detective",
      "a dragon",
      "a magic wand",
      "a pop song",
      "a stage curtain",
      "a television remote",
      "a book club",
      "a dance battle",
      "a comedy show",
      "a movie ticket",
      "a villain",
      "a ghost story",
      "a treasure map",
      "a karaoke night",
      "a red carpet",
      "a fairy tale",
      "a circus act",
      "a dramatic pause",
    ],
    hard: [
      "a plot twist",
      "a cliffhanger",
      "a musical number",
      "a secret identity",
      "a fake mustache disguise",
      "a director's cut",
      "a unreliable narrator",
      "a method actor",
      "a time-loop episode",
      "a fantasy quest",
      "a dystopian city",
      "a haunted theater",
      "a love triangle",
      "a fan theory",
      "a silent film scene",
      "a celebrity scandal",
      "a book adaptation",
      "a rejected audition",
      "a cursed artifact",
      "a surprise cameo",
    ],
    extreme: [
      "a fourth-wall break",
      "a multiverse crossover",
      "a meta-narrative",
      "a genre parody",
      "a unreliable prophecy",
      "a fictional language",
      "a canceled spin-off",
      "a cult classic reference",
      "a director's hidden symbol",
      "a tragic antihero arc",
      "a bottle episode",
      "a dream-within-a-dream scene",
      "a post-credit revelation",
      "a sentient stage prop",
      "a forbidden fan edit",
      "a villain redemption debate",
      "a lost pilot episode",
      "a fake documentary crew",
      "a cursed encore",
      "an impossible continuity error",
    ],
  },
  "abstract-concepts": {
    normal: [
      "love",
      "fear",
      "time",
      "luck",
      "teamwork",
      "jealousy",
      "patience",
      "honesty",
      "freedom",
      "confusion",
      "hope",
      "anger",
      "trust",
      "memory",
      "friendship",
      "silence",
      "curiosity",
      "choice",
      "balance",
      "surprise",
    ],
    hard: [
      "democracy",
      "inflation",
      "gravity",
      "privacy",
      "identity",
      "justice",
      "nostalgia",
      "pressure",
      "responsibility",
      "risk",
      "competition",
      "forgiveness",
      "ambition",
      "consequence",
      "routine",
      "authority",
      "sacrifice",
      "reputation",
      "equality",
      "strategy",
    ],
    extreme: [
      "cognitive dissonance",
      "moral hazard",
      "entropy",
      "the observer effect",
      "collective memory",
      "existential dread",
      "paradox",
      "survivorship bias",
      "social contract",
      "delayed gratification",
      "false consensus",
      "emergence",
      "epistemic humility",
      "the uncanny valley",
      "game theory",
      "path dependency",
      "symbolic power",
      "opportunity cost",
      "infinite regress",
      "liminal space",
    ],
  },
};

function titleCaseDifficulty(difficulty: DifficultyId) {
  return DIFFICULTIES.find((item) => item.id === difficulty)?.name ?? difficulty;
}

export function getCategoryName(categoryId: CategoryId) {
  return CATEGORY_PACKS.find((category) => category.id === categoryId)?.name ?? categoryId;
}

export function getDifficultyName(difficulty: DifficultyId) {
  return titleCaseDifficulty(difficulty);
}

export function generateCardPack(
  categoryId: CategoryId,
  difficulty: DifficultyId,
  count = CARDS_PER_PACK,
): GeneratedCard[] {
  const categoryName = getCategoryName(categoryId);
  const subjectList = subjects[categoryId][difficulty];
  const contexts = contextTemplates[categoryId][difficulty];
  const templates = frameTemplates[difficulty];
  const cards: GeneratedCard[] = [];

  for (const subject of subjectList) {
    for (const template of templates) {
      for (const context of contexts) {
        const text = `${template.replace("{subject}", subject)} ${context}`;
        cards.push({
          id: `${categoryId}-${difficulty}-${cards.length + 1}`,
          text,
          categoryId,
          categoryName,
          difficulty,
        });
      }
    }
  }

  if (cards.length < count) {
    throw new Error(`Card pack ${categoryId}/${difficulty} only generated ${cards.length} cards.`);
  }

  return cards.slice(0, count);
}

export function getPackCardCount() {
  return CARDS_PER_PACK;
}

export function getTotalCardCount() {
  return CATEGORY_PACKS.length * DIFFICULTIES.length * CARDS_PER_PACK;
}
